apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: airflowargo11
  namespace: argocd
spec:
  project: default
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: airflowargo11
  source:
    repoURL: 'https://github.com/DevOps-Studio-works/AirFlow.git'
    path: airflow-chart-1.11.0/chart
    targetRevision: dev  # or specify a Git branch, tag, or commit
    helm:
      version: v3
      releaseName: airflowargo11
      valueFiles: 
      - values.yaml
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

